### ISSUE TITLE
Map (North) Orientation bug

### ISSUE THREAD

**Issue by SaadmLMC** [martin-braun-net/google_maps_place_picker_mb#55]
Once the orientation icon is tapped inside the map, the screen adjusts to the correct orientation, flickers for a few seconds and disappears. The icon, reappears again after map orientation is manually adjusted.

1. Go to Maps
2. Click on North Icon Button
3. The button starts to flicker
4. Verbose error report can be found

**Expected behavior**
The button should change the orientation without flickering and disappearing.

**Device/Emulator/Simulator (and architecture)**
Pixel 5 x86_64 Emulator, 
iPhone 14 Simulator, 
Galaxy Tab Device, 
iPhone 14 Device

**Comment by martin-braun** [comment]
@SaadmLMC 

Don't know what you mean, the compass orientation is disabled. I tried to set `compassEnable: true` on the `GoogleMap` widget, but it won't show the needle icon. What "North Icon Button" are you talking about?
