### ISSUE TITLE
_searchByCameraLocation google_map_place_picker.dart:124 Null check operator used on a null value

### ISSUE THREAD

**Issue by giorgio79** [martin-braun-net/google_maps_place_picker_mb#67]
This bug popped up in my Crashlytics. No clue how to repro it. Logging it for now.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at GoogleMapPlacePicker._searchByCameraLocation(google_map_place_picker.dart:124)
       at GoogleMapPlacePicker._buildGoogleMapInner.<fn>.<fn>(google_map_place_picker.dart:243)

![image](https://github.com/martin-braun-net/google_maps_place_picker_mb/assets/283347/4e512568-acf7-4bb8-bbae-381b1ad792a2)

**Comment by martin-braun** [comment]
It also seems the app crashes when you press the back button while a place is being resolved, might be related.

**Comment by martin-braun** [comment]
Issue should be fixed in the next release.
