### ISSUE TITLE
Dependency (Compatibility) Issue

### ISSUE THREAD

**Issue by mianazeemdaula** [martin-braun-net/google_maps_place_picker_mb#71]
**Describe the bug**
google_maps_place_picker_mb >=2.0.0-mb.18 <3.0.1 depends on location ^4.4.0 and google_maps_place_picker_mb >=2.0.0-mb.2 <2.0.0-mb.18 depends on location ^4.3.0, google_maps_place_picker_mb >=2.0.0-mb.2 <3.0.1 requires location ^4.3.0.

**Screenshots**

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19045.2006], locale en-US)
    • Flutter version 3.13.3 on channel stable at D:\programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\ITSO\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2006]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.69

[√] Network resources
    • All expected network resources are available.

**Comment by martin-braun** [comment]
You are using an ancient version. Upgrade all your packages please.
