### ISSUE TITLE
Get directions.

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [martin-braun-net/google_maps_place_picker_mb#75]
I want users to get direction for the pointed location how can i do so ?

**Comment by martin-braun** [comment]
Trigonometry, my friend.

Receive the current location (lat, lng) without this component on your own, here is how to do it: https://github.com/martin-braun-net/google_maps_place_picker_mb/blob/546ee1348bdf7c9e9433e79b51adc76ff6ffe5c3/lib/providers/place_provider.dart#L44 (just use the same Geolocator in your app)

Then, using this component, subscribe to the `onPlacePicked` callback, like so: https://github.com/martin-braun-net/google_maps_place_picker_mb/blob/546ee1348bdf7c9e9433e79b51adc76ff6ffe5c3/example/lib/main.dart#L183 (the result contains geometry lat lng of the target location)

I would then calculate a normalized vector between those two points using https://pub.dev/packages/vector_math. Eventually, the normalized vector needs to be converted to a direction in degrees, see https://www.cuemath.com/direction-of-a-vector-formula/

This is an unrelated problem, so I cannot provide in-depth support on this, but I hope that you have a general idea how to move from this point. Please feel free to share your results for others who find your post in the future, though.
